apiVersion: v1
kind: Pod
metadata:
  name: laravel-quotations-microservice
  labels:
    environment: production
spec:
  containers:
    - name: laravel-quotations-microservice
      image: ezekielreginio/laravel-quotations-microservice
      ports:
        - name: open-project
          containerPort: 8182
          protocol: TCP
      volumeMounts:
        - mountPath: "/var/openproject"
          name: data
      livenessProbe:
        tcpSocket:
          port: 8182
        initialDelaySeconds: 600
        timeoutSeconds: 1
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: open-project-storage-claim
  imagePullSecrets:
    - name: regcred